version: '1'
services:
  java-server:
    build: ./docker/java
    container_name: java
    restart: always
    ports:
      - "8080:8080"

  db:
    build: /docker/db
    container_name: libDB
    restart: always
    environment:
      POSTGRES_DB: "litres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "rootuser"
    ports:
      - "5432:5432"